<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 9" tests="1" total_time="Finished in: 0.00 secs."/>
    <test location="/Users/jeff/Documents/workspaces/dme/track_logger_converter/tests/parsers/can_frame_parser_test.py" status="error" test="CanFrameParserTest.testFrame242" time="">
        <stdout/>
        <stderr>
            <![CDATA[Traceback (most recent call last):
  File "/Users/jeff/Documents/workspaces/dme/track_logger_converter/tests/parsers/can_frame_parser_test.py", line 19, in testFrame242
    test_extractor.extractData(test_fields, CanFrameParserTest.test_state)
  File "/Users/jeff/Documents/workspaces/dme/track_logger_converter/parsers/can_frame_parser.py", line 23, in extractData
    state.put(DataState.names[DataState.names.Clutch], clutch_pedal)
AttributeError: 'DataState' object has no attribute 'put'
]]>
        </stderr>
    </test>
    <launch mode="run">
        <launch_memento>
            <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="track_logger_converter can_frame_parser_test.py"/>
]]>
        </launch_memento>
    </launch>
</pydev-testsuite>
