<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="0" failures="1" finished="true" name="Test Run: 74" tests="1" total_time="Finished in: 0.00 secs."/>
    <test location="/Users/jeff/Documents/workspaces/dme/track_logger_converter/tests/parsers/nmea_parser_test.py" status="fail" test="NmeaParserTest.test_rmc_1" time="">
        <stdout/>
        <stderr>
            <![CDATA[Traceback (most recent call last):
  File "/Users/jeff/Documents/workspaces/dme/track_logger_converter/tests/parsers/nmea_parser_test.py", line 25, in test_rmc_1
    self.assertEqual(self.test_state.get_data_item(DataState.get_data_name_at_idx(DataState.names.GPS_Time)), '04:03:38.445')
AssertionError: '04:03:38' != '04:03:38.445'
- 04:03:38
+ 04:03:38.445
?         ++++

]]>
        </stderr>
    </test>
    <launch mode="run">
        <launch_memento>
            <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="track_logger_converter nmea_parser_test.py"/>
]]>
        </launch_memento>
    </launch>
</pydev-testsuite>
